import type { Metadata } from "next"
import "./globals.css"
import { Montserrat, Geist } from "next/font/google"
import { cn } from "@/lib/utils";
import { ToastContainer } from "react-toastify";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr" className={cn("font-sans", geist.variable)}>
      <body className={montserrat.className}>
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}